calc.cpp File Reference
#include <iostream>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `GeneralNumber.h`
*
Functions
int main (int argc, char *argv[])
int start_calculator ()
GeneralNumber * calculate (GeneralNumber *fnum, GeneralNumber *snum, char *oprtr)
Function Documentation
GeneralNumber* calculate (GeneralNumber * fnum, GeneralNumber * snum, char * oprtr)
Consumes two GeneralNumbers and an operation (string form) and then and then uses helper functions to apply operations on the given objects and then9 return the answer in GeneralNumber object form
Parameters
fnum Number the second number will be applied on by the operation
snum Number that will be applied on the first number by the operation
oprtr Operator to be applied in string form
Returns
Answer of the operation on the two numbers in GeneralNumber form
References GeneralNumber::add(), GeneralNumber::divide(), GeneralNumber::multiply(), and GeneralNumber::subtract().
Referenced by start_calculator().
int main (int argc, char * argv[])
Calculator program using GeneralNumber class and its subclasses.
Parameters
argc Number of words on the command line.
argv Array of pointers to these words.
References start_calculator().
int start_calculator ()
Asks user to enter two numbers (arguments in string form) and an operation (char) and then parses those number to GeneralNumber form and then calculates the result in accordance with the operation given
Returns
0 or 1 to indicate when users want to end calculator (loop)
References calculate(), MAX_DIGITS_OR_CHARACTERS_ENTERED, GeneralNumber::parse(), and GeneralNumber::toString().
Referenced by main().