GeneralDouble Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralDouble ()
GeneralDouble (double value)
char * toString () const
char * foo () const
GeneralLong * toGeneralLong () const
GeneralRational * toGeneralRational () const
GeneralDouble * toGeneralDouble () const
GeneralNumber * add (GeneralNumber *gn) const
GeneralNumber * subtract (GeneralNumber *gn) const
GeneralNumber * multiply (GeneralNumber *gn) const
GeneralNumber * divide (GeneralNumber *gn) const
Private Attributes
double value
Additional Inherited Members
Constructor & Destructor Documentation
GeneralDouble::GeneralDouble ()
Default constructor for GeneralDouble
GeneralDouble::GeneralDouble (double value)
Constructor for GeneralDouble
Parameters
value Decimal Number to store in the object
Member Function Documentation
GeneralNumber * GeneralDouble::add (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralDouble and then adds the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralDouble of the sum
Parameters
gn GeneralNumber we want added to the GeneralLong
Returns
Pointer to the sum in GeneralDouble form
Implements GeneralNumber .
References GeneralNumber::toGeneralDouble(), and value.
Referenced by main().
GeneralNumber * GeneralDouble::divide (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralDouble and then divides the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralSouble of the quotient
Parameters
gn GeneralNumber we want to divide the GeneralDouble with
Returns
Pointer to the quotient in GeneralDouble form
Implements GeneralNumber .
References GeneralNumber::toGeneralDouble(), and value.
char * GeneralDouble::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
GeneralNumber * GeneralDouble::multiply (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralDouble and then multiplies the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralDouble of the product
Parameters
gn GeneralNumber we want multiplied to the GeneralDouble
Returns
Pointer to the product in GeneralDouble form
Implements GeneralNumber .
References GeneralNumber::toGeneralDouble(), and value.
GeneralNumber * GeneralDouble::subtract (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralDouble and then subtracts the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralNumber of the difference
Parameters
gn GeneralNumber we want subtracted from the GeneralDouble
Returns
Pointer to the sum in GeneralDouble form
Implements GeneralNumber .
References GeneralNumber::toGeneralDouble(), and value.
GeneralDouble * GeneralDouble::toGeneralDouble () const [virtual]
Generates an equivalent GeneralDouble
Returns
Pointer to a freshly-allocated GeneralDouble object
Implements GeneralNumber .
GeneralLong * GeneralDouble::toGeneralLong () const [virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Implements GeneralNumber .
GeneralRational * GeneralDouble::toGeneralRational () const [virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Implements GeneralNumber .
char * GeneralDouble::toString () const [virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Implements GeneralNumber .
References MAX_DIGITS_IN_DOUBLE.
Referenced by main().
Member Data Documentation
double GeneralDouble::value [private]
Referenced by add(), divide(), multiply(), and subtract().
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp