GeneralRational Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralRational ()
GeneralRational (long top, long bottom)
char * toString () const
char * foo () const
GeneralLong * toGeneralLong () const
GeneralRational * toGeneralRational () const
GeneralDouble * toGeneralDouble () const
void toCanonicalForm ()
GeneralNumber * add (GeneralNumber *gn) const
GeneralNumber * subtract (GeneralNumber *gn) const
GeneralNumber * multiply (GeneralNumber *gn) const
GeneralNumber * divide (GeneralNumber *gn) const
Private Attributes
long top
long bottom
Additional Inherited Members
Constructor & Destructor Documentation
GeneralRational::GeneralRational ()
Default constructor for GeneralRational
GeneralRational::GeneralRational (long top, long bottom)
Constructor for GeneralRational
Parameters
top Numerator to store in the object
bottom Denominator to store in the object
Member Function Documentation
GeneralNumber * GeneralRational::add (GeneralNumber * gn) const [virtual]
Converts GeneralNumber passed in to GeneralRational and adds its value with the converted GeneralRation by the help of lcm() helper function.
Parameters
gn GeneralNumber we wanted added to the GeneralRational
Returns
Pointer to the sum in GeneralRational form
Implements GeneralNumber .
References bottom, find_lcd(), toCanonicalForm(), GeneralNumber::toGeneralRational(), and top.
Referenced by main().
GeneralNumber * GeneralRational::divide (GeneralNumber * gn) const [virtual]
Converts GeneralNumber passed in to GeneralRational and divides its value with the converted GeneralRational by inverting the top and bottom values of the converted value and multiplying the object with it. Then returns the result in GeneralRational form.
Parameters
gn GeneralNumber we wanted to divide the GeneralRational with
Returns
Pointer to the quotient in GeneralRational form
Implements GeneralNumber .
References bottom, toCanonicalForm(), GeneralNumber::toGeneralRational(), and top.
char * GeneralRational::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
GeneralNumber * GeneralRational::multiply (GeneralNumber * gn) const [virtual]
Converts GeneralNumber passed in to GeneralRational and multiplies its top and bottom values with the converted GeneralRational's top and bottom values and then return's the result in GeneralRational form.
Parameters
gn GeneralNumber we wanted multiplied to the GeneralRational
Returns
Pointer to the sum in GeneralRational form
Implements GeneralNumber .
References bottom, toCanonicalForm(), GeneralNumber::toGeneralRational(), and top.
GeneralNumber * GeneralRational::subtract (GeneralNumber * gn) const [virtual]
Converts GeneralNumber passed in to GeneralRational and subtracts its value with the converted GeneralRational by the help of lcm() helper function.
Parameters
gn GeneralNumber we wanted subtracted from the GeneralRational
Returns
Pointer to the sum in GeneralRational form
Implements GeneralNumber .
References bottom, find_lcd(), toCanonicalForm(), GeneralNumber::toGeneralRational(), and top.
void GeneralRational::toCanonicalForm ()
Finds the GCD of the nominator and denominator and divides them with their GCD to fing their lowest term. Also arranges position of negative sign
Returns
Same GeneralRational but in lowest term/canonical form
References find_gcd(), and gcd().
Referenced by add(), divide(), main(), multiply(), and subtract().
GeneralDouble * GeneralRational::toGeneralDouble () const [virtual]
Generates an equivalent GeneralDouble
Returns
Pointer to a freshly-allocated GeneralDouble object
Implements GeneralNumber .
GeneralLong * GeneralRational::toGeneralLong () const [virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Implements GeneralNumber .
Referenced by main().
GeneralRational * GeneralRational::toGeneralRational () const [virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Implements GeneralNumber .
char * GeneralRational::toString () const [virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Implements GeneralNumber .
References MAX_DIGITS_IN_LONG.
Referenced by main().
Member Data Documentation
long GeneralRational::bottom [private]
Referenced by add(), divide(), multiply(), and subtract().
long GeneralRational::top [private]
Referenced by add(), divide(), multiply(), and subtract().
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp