GeneralNumber Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralNumber ()
virtual char * toString () const =0
char * foo () const
virtual GeneralLong * toGeneralLong () const =0
virtual GeneralRational * toGeneralRational () const =0
virtual GeneralDouble * toGeneralDouble () const =0
virtual GeneralNumber * add (GeneralNumber *g) const =0
virtual GeneralNumber * subtract (GeneralNumber *g) const =0
virtual GeneralNumber * multiply (GeneralNumber *g) const =0
virtual GeneralNumber * divide (GeneralNumber *g) const =0
Static Public Member Functions
static GeneralNumber * parse (const char *s)
Constructor & Destructor Documentation
GeneralNumber::GeneralNumber ()
Default constructor for GeneralNumber
Member Function Documentation
GeneralNumber * GeneralNumber::add (GeneralNumber * g) const [pure virtual]
Returns pointer to GeneralNumber
Returns
Pointer to the GeneralNumber passed in
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by calculate().
GeneralNumber * GeneralNumber::divide (GeneralNumber * g) const [pure virtual]
Returns pointer to GeneralNumber
Returns
Pointer to the GeneralNumber passed in
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by calculate().
char * GeneralNumber::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
Referenced by main().
GeneralNumber * GeneralNumber::multiply (GeneralNumber * g) const [pure virtual]
Returns pointer to GeneralNumber
Returns
Pointer to the GeneralNumber passed in
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by calculate().
GeneralNumber * GeneralNumber::parse (const char * s) [static]
Parses a string representing a GeneralNumber
Parameters
s The string to parse
Returns
Pointer to a newly-allocated object of the correct subclass, or null pointer if unable to parse.
Referenced by main(), and start_calculator().
GeneralNumber * GeneralNumber::subtract (GeneralNumber * g) const [pure virtual]
Returns pointer to GeneralNumber
Returns
Pointer to the GeneralNumber passed in
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by calculate().
GeneralDouble * GeneralNumber::toGeneralDouble () const [pure virtual]
Generates an equivalent GeneralDouble
Returns
Pointer to a freshly-allocated GeneralDouble object
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by GeneralDouble::add(), GeneralDouble::divide(), GeneralDouble::multiply(), and GeneralDouble::subtract().
GeneralLong * GeneralNumber::toGeneralLong () const [pure virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by GeneralLong::add(), GeneralLong::divide(), main(), GeneralLong::multiply(), and GeneralLong::subtract().
GeneralRational * GeneralNumber::toGeneralRational () const [pure virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by GeneralRational::add(), GeneralRational::divide(), GeneralRational::multiply(), and GeneralRational::subtract().
char * GeneralNumber::toString () const [pure virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Implemented in GeneralDouble , GeneralRational , and GeneralLong .
Referenced by main(), and start_calculator().
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp
gnparse.cpp