GeneralLong Class Reference
#include <GeneralNumber.h>
Public Member Functions
GeneralLong ()
GeneralLong (long value)
char * toString () const
char * foo () const
GeneralLong * toGeneralLong () const
GeneralRational * toGeneralRational () const
GeneralDouble * toGeneralDouble () const
GeneralNumber * add (GeneralNumber *gn) const
GeneralNumber * subtract (GeneralNumber *gn) const
GeneralNumber * multiply (GeneralNumber *gn) const
GeneralNumber * divide (GeneralNumber *gn) const
Private Attributes
long value
Additional Inherited Members
Constructor & Destructor Documentation
GeneralLong::GeneralLong ()
Default constructor for GeneralLong
GeneralLong::GeneralLong (long value)
Constructor for GeneralLong
Parameters
value Number to store in the object
Member Function Documentation
GeneralNumber * GeneralLong::add (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralLong and then adds the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralLong of the sum
Parameters
gn GeneralNumber we want added to the GeneralLong
Returns
Pointer to the sum in GeneralLong form
Implements GeneralNumber .
References GeneralNumber::toGeneralLong(), and value.
GeneralNumber * GeneralLong::divide (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralLong and then divides the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralLong of the quotient
Parameters
gn GeneralNumber we want to divide the GeneralLong with
Returns
Pointer to the quotient in GeneralLong form
Implements GeneralNumber .
References GeneralNumber::toGeneralLong(), and value.
char * GeneralLong::foo () const
Demonstrates a non-virtual function.
Returns
Freshly-allocated C-stype string
Referenced by main().
GeneralNumber * GeneralLong::multiply (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralLong and then multiplies the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralLong of the product
Parameters
gn GeneralNumber we want multiplied to the GeneralLong
Returns
Pointer to the product in GeneralLong form
Implements GeneralNumber .
References GeneralNumber::toGeneralLong(), and value.
GeneralNumber * GeneralLong::subtract (GeneralNumber * gn) const [virtual]
Converts any GeneralNumber to GeneralLong and then subtracts the value of the object it is invoked on to the value found in the object it converted Then returns generates a GeneralNumber of the difference
Parameters
gn GeneralNumber we want subtracted from the GeneralLong
Returns
Pointer to the sum in GeneralLong form
Implements GeneralNumber .
References GeneralNumber::toGeneralLong(), and value.
GeneralDouble * GeneralLong::toGeneralDouble () const [virtual]
Generates an equivalent GeneralDouble
Returns
Pointer to a freshly-allocated GeneralDouble object
Implements GeneralNumber .
GeneralLong * GeneralLong::toGeneralLong () const [virtual]
Generates an equivalent GeneralLong
Returns
Pointer to a freshly-allocated GeneralLong object
Implements GeneralNumber .
GeneralRational * GeneralLong::toGeneralRational () const [virtual]
Generates an equivalent GeneralRational
Returns
Pointer to a freshly-allocated GeneralRational object
Implements GeneralNumber .
Referenced by main().
char * GeneralLong::toString () const [virtual]
Generates a printable representation of the object.
Returns
Freshly-allocated C-stype string
Implements GeneralNumber .
References MAX_DIGITS_IN_LONG.
Referenced by main().
Member Data Documentation
long GeneralLong::value [private]
Referenced by add(), divide(), multiply(), and subtract().
The documentation for this class was generated from the following files:
GeneralNumber.h
GeneralNumber.cpp