GeneralNumber.cpp File Reference
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `GeneralNumber.h`
*
Functions
long find_gcd (long a, long b)
long find_lcd (long a, long b)
Function Documentation
long find_gcd (long a, long b)
Finds the Greatest Common Divisor of two numbers
Parameters
a One of two numbers we want the GCD of
b One of two numbers we want the GCD of
Returns
The GCD of the two numbers in long format
Referenced by find_lcd(), and GeneralRational::toCanonicalForm().
long find_lcd (long a, long b)
Finds the Least Common Denominator of two numbers
Parameters
a One of two numbers we want LCD of
b One of two numbers we want LCD of
Returns
The GCD of the two numbers in long format
References find_gcd().
Referenced by GeneralRational::add(), and GeneralRational::subtract().