GeneralNumber.h File Reference
Classes
class GeneralNumber
class GeneralLong
class GeneralRational
class GeneralDouble
Macros
#define MAX_DIGITS_IN_LONG (20)
#define MAX_DIGITS_IN_DOUBLE (20)
#define MAX_DIGITS_OR_CHARACTERS_ENTERED (20)
Functions
long find_gcd (long a, long b)
long find_lcd (long a, long b)
int start_calculator ()
GeneralNumber * calculate (GeneralNumber *fnum, GeneralNumber *snum, char *oprtr)
Macro Definition Documentation
#define MAX_DIGITS_IN_DOUBLE (20)
Referenced by GeneralDouble::toString().
#define MAX_DIGITS_IN_LONG (20)
Referenced by GeneralLong::toString(), and GeneralRational::toString().
#define MAX_DIGITS_OR_CHARACTERS_ENTERED (20)
Referenced by start_calculator().
Function Documentation
GeneralNumber* calculate (GeneralNumber * fnum, GeneralNumber * snum, char * oprtr)
Consumes two GeneralNumbers and an operation (string form) and then and then uses helper functions to apply operations on the given objects and then9 return the answer in GeneralNumber object form
Parameters
fnum Number the second number will be applied on by the operation
snum Number that will be applied on the first number by the operation
oprtr Operator to be applied in string form
Returns
Answer of the operation on the two numbers in GeneralNumber form
References GeneralNumber::add(), GeneralNumber::divide(), GeneralNumber::multiply(), and GeneralNumber::subtract().
Referenced by start_calculator().
long find_gcd (long a, long b)
Finds the Greatest Common Divisor of two numbers
Parameters
a One of two numbers we want the GCD of
b One of two numbers we want the GCD of
Returns
The GCD of the two numbers in long format
Referenced by find_lcd(), and GeneralRational::toCanonicalForm().
long find_lcd (long a, long b)
Finds the Least Common Denominator of two numbers
Parameters
a One of two numbers we want LCD of
b One of two numbers we want LCD of
Returns
The GCD of the two numbers in long format
References find_gcd().
Referenced by GeneralRational::add(), and GeneralRational::subtract().
int start_calculator ()
Asks user to enter two numbers (arguments in string form) and an operation (char) and then parses those number to GeneralNumber form and then calculates the result in accordance with the operation given
Returns
0 or 1 to indicate when users want to end calculator (loop)
References calculate(), MAX_DIGITS_OR_CHARACTERS_ENTERED, GeneralNumber::parse(), and GeneralNumber::toString().
Referenced by main().