#define MAX_CHARS 10 //Maximum amount of characters generated by random_string()


// Class "prototypes" to solve the forward reference problem:
class Tree;
class Tnode;

// The parent class:

class Tree {
 public:
  Tnode* root;
  Tree();
  void add(const char* data);
  void printAscending() const;
  void printAscendingHelper(Tnode* node) const;
  void freeTree();
  void freeTreeHelper(Tnode* node);
};


class Tnode {
 public:
  const char* data;
  Tnode* left;
  Tnode* right;
  int count;
  Tnode(const char* stringData);
  void add(const char* data);
  
};

char random_character();
char *random_string(int length);
int random_integer(int max);

