Stack Class Reference
#include <objstack.h>
Public Member Functions
Stack (int max_cells)
~Stack ()
int push (void *ptr)
void * pop ()
void * peek ()
Public Attributes
void ** stack_base
void ** next
int max_cells
int cells_used
Detailed Description
Class to define a stack; each entry can hold a pointer to anything.
Constructor & Destructor Documentation
Stack::Stack (int max_cells)
Create a stack by initializing the fields of the object, including allocating memory to hold the stack entries.
Parameters
max_cells Maximum entries in the stack
Stack::~Stack ()
Destructor: cleans up a Stack object by deleting the memory for holding the stack entries, but not the entries themselves.
Member Function Documentation
void * Stack::peek ()
Peek at top of stack, without popping
Returns
Top entry of the stack, NULL if stack is empty.
Referenced by main().
void * Stack::pop ()
Pops top of stack, and returns it.
Returns
Top entry of the stack, NULL if stack is empty.
Referenced by main().
int Stack::push (void * ptr)
Pushes a pointer onto a Stack.
Parameters
ptr Pointer to be pushed.
Returns
0 if successful, -1 if not.
Referenced by main().
Member Data Documentation
int Stack::cells_used
int Stack::max_cells
void** Stack::next
void** Stack::stack_base
The documentation for this class was generated from the following files:
objstack.h
objstack.cpp