objstacktest.cpp File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include `objstack.h`
*
#include `foo.h`
*
Functions
int main ()
Function Documentation
int main ()
References Stack::peek(), Stack::pop(), Stack::push(), and Foo::toString().