Tree Class Reference
#include <Tree.h>
Public Member Functions
Tree ()
void add (const char *data)
void printAscending () const
void printAscendingHelper (Tnode *node) const
void freeTree ()
void freeTreeHelper (Tnode *node)
Public Attributes
Tnode * root
Constructor & Destructor Documentation
Tree::Tree ()
Default constructor for GeneralNumber
References root.
Member Function Documentation
void Tree::add (const char * data)
Adds given string (C style) to a newly instantiated node and adds it to the tree if the tree is empty. If the tree is not empty, it calls the add function on the root Tnode.
Parameters
data C style string to add to tree as data
References Tnode::add(), and root.
Referenced by main().
void Tree::freeTree ()
Frees the nodes in the tree using postorder transversal. This function has a helper function which accepts a node and uses postorder transveral by recursion to free all nodes that brach out from the given node. If tree is empty, it prints an appropriate message.
References freeTreeHelper(), and root.
Referenced by main().
void Tree::freeTreeHelper (Tnode * node)
Accepts a node and uses postorder transveral by recursion to free all nodes that brach out from the given node. This function should not be called because it is a helper function.
Parameters
node Is the root node of the tree you want to free
References Tnode::data, Tnode::left, and Tnode::right.
Referenced by freeTree().
void Tree::printAscending () const
Prints the tree in ascending order of values using inorder transversal on the tree. Has a helper function which accepts a node and prints recursion. This is the main function that is used to print the tree.
References printAscendingHelper(), and root.
Referenced by main().
void Tree::printAscendingHelper (Tnode * node) const
This is a helper function that prints the tree in ascending order of values using inorder transversal on the tree. Uses recursion for inorder transversal. This function should not be called because it is a helper function.
Parameters
node Is the root node of the tree you want to print
References Tnode::data, Tnode::left, and Tnode::right.
Referenced by printAscending().
Member Data Documentation
Tnode* Tree::root
Referenced by add(), freeTree(), printAscending(), and Tree().
The documentation for this class was generated from the following files:
Tree.h
Tree.cpp