objqueuetest.cpp File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include `objqueue.h`
*
#include `foo.h`
*
Functions
int main ()
Function Documentation
int main ()
References Queue::dequeue(), Queue::enqueue(), and Foo::toString().