Tree.h File Reference
Classes
class Tree
class Tnode
Macros
#define MAX_CHARS 10
Functions
char random_character ()
char * random_string (int length)
int random_integer (int max)
Macro Definition Documentation
#define MAX_CHARS 10
Referenced by main().
Function Documentation
char random_character ()
Generates and returns a random capital letter/character by first generating a random number and using it as an index to randomly select a character from an array of characters containing all the capital letters
Returns
A single character. That is a randomly selected capital letter
References random_character().
Referenced by random_character(), and random_string().
int random_integer (int max)
Return a random number from 0 to maximum specified number.
Parameters
max Maximum specified value for random number generator
Returns
random number
char* random_string (int length)
Creates, allocates and returns a pointer to a random string it has created. The string consists of all capital letters, and always a length that the user passes as a parameter. It uses the function random_character() repeatedly to generate a string of size length.
Parameters
length Size of the newly genrated string
Returns
A pointer to the newly allocated and randomly generated string.
References random_character().
Referenced by main().