treetest.cpp File Reference
#include <iostream>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include `Tree.h`
*
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Program to demonstrate the Tree and Tnode class and their methods.
Parameters
argc Number of words on the command line.
argv Array of pointers to these words.
References Tree::add(), Tnode::data, Tree::freeTree(), Tnode::left, Tree::printAscending(), and Tnode::right.