sort_ascending.h File Reference
Functions
void sort_ascending (int *array_to_sort, int array_size)
int random_integer (int max)
int * random_array (int size, int max)
Function Documentation
int* random_array (int size, int max)
Generate a specified size array filled with random numbers
Parameters
size Size of array created
max Maximum value for each random numbers generated
Returns
randomly generated array
References random_integer().
Referenced by main().
int random_integer (int max)
Return a random number from 0 to maximum specified number.
Parameters
max Maximum specified value for random number generator
Returns
random number
Referenced by random_array().
void sort_ascending (int * array_to_sort, int array_size)
File sort_ascending.h
Author
Adonay Resom (Started by Mike Ciaraldi)
Header file for functions that sort arrays in ascending order.
file sort_ascending.c
Author
Adonay Resom (Started by Mike Ciaraldi)
Functions for sorting arrays in ascending order.Sorts an array's elements in ascending order
Parameters
array_to_sort A pointer to an integer array containing integers to get sorted
array_size The maximum number of elements allowed in this array