main.c File Reference
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <time.h>
*
#include `mystring.h`
*
#include `structs.h`
*
Macros
#define MAX_CHARS 100
Functions
int main ()
Macro Definition Documentation
#define MAX_CHARS 100
main.c Program to demonstrate structs
Author
Adonay Resom
Referenced by main().
Function Documentation
int main ()
Main program Demostrates use and processes on the struct Employee
Returns
0 Indicates success. 1 Indicates failure
References duplicate_employee_array_deep(), duplicate_employee_array_shallow(), free_employee_array(), make_employee(), MAX_CHARS, print_employee(), print_employee_array(), random_employee(), random_employee_array(), and random_string().