mystring.h File Reference
Functions
char * mystrdup (const char *src)
size_t mystrlen (const char *string)
char * mystrcpy (char *dest, const char *src)
char * mystrcat (char *dest, const char *src)
char * mystrncat (char *dest, const char *src, size_t n)
char * mystrncpy (char *dest, const char *src, size_t n)
char * mystrndup (const char *src, size_t n)
char random_character ()
char * random_string (int length)
int random_integer (int max)
Function Documentation
char* mystrcat (char * dest, const char * src)
Concatenates two strings (source and destination strings)by adding the source string to the destination string by finding the position of the terminating byte of the destination string and adding the source string starting from that position.
Parameters
src The source string from which all the charachters will be added
dest String to which the charachters of the source string will be copied
Returns
Destination string which has all the charachters of the source string added to it
find the length of the destination to be able to find the position of the terminating byte
References mystrlen().
Referenced by main().
char* mystrcpy (char * dest, const char * src)
Consumes two strings and copies all of the charachters (including the terminating byte '/0') from the source string to the destination string.
Parameters
src The source string that will be copied to the destination
dest String to which the charachters of the source string will be copied
Returns
The destination string which has all charachters copied from the source string
Referenced by make_employee(), and mystrdup().
char* mystrdup (const char * src)
mystring.h
Author
Adonay Resom (started by Mike Ciaraldi) Prototypes of my own version of some of the C-style string functions
mystring.c
Author
Adonay Resom (started by Mike Ciaraldi) My own versions of some of the C-style string functions Duplicates a C-style string.
Parameters
src Pointer to string to be copied
Returns
Pointer to freshly-allocated string containing a duplicate of src or null if no memory is available
References mystrcpy(), and mystrlen().
Referenced by main().
size_t mystrlen (const char * s)
Consumes a string and calculates the length of it(number of characters in a string). It uses a loop that keeps on checking if the character on the index i (loop counter) of the string is not the terminating byte '\0', and keeps on adding 1 to a length variable till it is.
Parameters
string String which its length will be calculate
Returns
number of charachters (length) of the string in form of size_t (used for counting because cant be negative)
Referenced by mystrcat(), mystrdup(), mystrncat(), and random_character().
char* mystrncat (char * dest, const char * src, size_t n)
Concatenates two strings (source and destination)but only adds n bytes of the source string to the destination. It finds the position of the terminating byte of the destination string and adds n bytes of the source string starting from that position.
Parameters
src The source string from which all the charachters will be added
dest String to which the charachters of the source string will be copied
n maximum number of charachter to add from source string
Returns
Destination string which has all the charachters of the source string added to it
find the length of the destination to be able to find the position of the terminating byte
References mystrlen().
Referenced by main().
char* mystrncpy (char * dest, const char * src, size_t n)
Consumes two strings and copies n number of charachters to the destination (starting from the beginning) from the source string to the destination string.
Parameters
src The source string that will be copied to the destination
dest String to which the charachters of the source string will be copied
n Maximum number of charachters allowed to copy from source string
Returns
The destination string which has n number of charachters copied from the source string
Referenced by main(), and mystrndup().
char* mystrndup (const char * src, size_t n)
Duplicates a C-style string.
Parameters
src Pointer to string to be copied
n Maximum charchters wanted to allocate
Returns
Pointer to freshly-allocated string containing a n characters from src string or null if no memory is available
References mystrncpy().
Referenced by main().
char random_character ()
Generates and returns a random capital letter/character by first generating a random number and using it as an index to randomly select a character from an array of characters containing all the capital letters
Returns
A single character. That is a randomly selected capital letter
References mystrlen(), and random_character().
Referenced by random_character(), and random_string().
int random_integer (int max)
Return a random number from 0 to maximum specified number.
Parameters
max Maximum specified value for random number generator
Returns
random number
Referenced by random_employee().
char* random_string (int length)
Creates, allocates and returns a pointer to a random string it has created. The string consists of all capital letters, and always a length that the user passes as a parameter. It uses the function random_character() repeatedly to generate a string of size length.
Parameters
length Size of the newly genrated string
Returns
A pointer to the newly allocated and randomly generated string.
References random_character().
Referenced by main(), and random_employee().