structs.c File Reference
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `mystring.h`
*
#include `structs.h`
*
Macros
#define MAX_NAME 10
Functions
struct Employee * make_employee (char *name, int birth_year, int start_year)
void print_employee (struct Employee *e)
struct Employee * random_employee ()
struct Employee ** random_employee_array (int count)
void print_employee_array (struct Employee **employee_array, int count)
struct Employee ** duplicate_employee_array_shallow (struct Employee **employee_array, int count)
void free_employee_array (struct Employee **employee_array, int count)
struct Employee ** duplicate_employee_array_deep (struct Employee **employee_array, int count)
Macro Definition Documentation
#define MAX_NAME 10
structs.c
Author
Adonay Resom Functions that process the struct Employee I created
Referenced by random_employee().
Function Documentation
struct Employee** duplicate_employee_array_deep (struct Employee ** employee_array, int count)
Consumes a pointer to an array containing pointers to Employee structs and the array size, and copies all data from the struct the pointers are pointing to, into a new Employee struct. And then it creates a new pointer pointing to the new Employee struct and stores the pointers into a new array. In short it performs a deep copy.
Parameters
employee_array Array contaning pointers to the struct getting copied
count size of array
Returns
A new array containing new pointers pointing to a new Employee struct the same data as the old one.
References Employee::birth_year, make_employee(), Employee::name, and Employee::starting_year.
Referenced by main().
struct Employee** duplicate_employee_array_shallow (struct Employee ** employee_array, int count)
Consumes a pointer to an array containing pointers to Employee structs and the array size, and copies those pointers into another array that it creates and allocates. The new array also holds pointers to Employee structs. In short it performs a shallow copy.
Parameters
employee_array Array contaning pointers getting copied
count size of array
Returns
A new array containing the same pointers pointing to the same Employee struct
Referenced by main().
void free_employee_array (struct Employee ** employee_array, int count)
Frees/Deallocates all the structs the pointer in the array are pointing to.
Parameters
employee_array Array contaning pointers getting deallocated
count size of array
Referenced by main().
struct Employee* make_employee (char * name, int birth_year, int start_year)
Creates and allocates an Employee struct and fill its fields with the paramaters passed into it
Parameters
name Name of the employee
birth_year The year of birth of the employee
start_year Year at which the employee got employed
Returns
Pointer to newly created and allocated Employee struct
References Employee::birth_year, mystrcpy(), Employee::name, and Employee::starting_year.
Referenced by duplicate_employee_array_deep(), main(), and random_employee().
void print_employee (struct Employee * e)
Consumes a pointer to an Employee struct and prints the values of the fields of that struct. In other words, prints Employee struct
Parameters
e Pointer to the Employee struct the user wants to be printed
References Employee::birth_year, Employee::name, and Employee::starting_year.
Referenced by main(), and print_employee_array().
void print_employee_array (struct Employee ** employee_array, int count)
Consumes a pointer to an array containing pointers to Employee structs and the array size, and uses those pointers to print each employee using the print_employee function created to print Employee struct fields.
Parameters
employee_array Array contaning pointers to the struct getting printed
count size of array
References print_employee().
Referenced by main().
struct Employee* random_employee ()
Generates randomly generated employee
Returns
A new Employee struct contaning randomly generated field values.
References Employee::birth_year, make_employee(), MAX_NAME, Employee::name, random_integer(), and random_string().
Referenced by main(), and random_employee_array().
struct Employee** random_employee_array (int count)
Generates an array of count(int) pointers pointing to randomly generated employees
Parameters
count integer representing amount of random employees generated
Returns
A new array containing pointer pointing to randomly generated employees.
References random_employee().
Referenced by main().